title = "An Angry Tech Blog"
logo = "img/mad_jam_text_random.png"

copyright = "CC BY-SA 4.0"

[author]
  name = "Mad Jam"
  headline = "WebDev, FOSS, DevOps, Gaming, Linux, and whatever else"
  bio = "FOSS Enthusiast - PC Gamer - Sys Admin - Tech Wrangler"
  image = "img/mad_jam_center.png"
  links = [
    { email = "mailto:notjamesdixon@gmail.com" },
    { github = "https://github.com/lemonase" },
    { linkedin = "https://linkedin.com/in/james-dixon-147431109/" },
    { goodreads = "https://www.goodreads.com/user/show/126275796-james" },
    { steam = "https://steamcommunity.com/id/thatonepyro" },
    { discord = "https://discord.gg/TNKD3QU2Jt" },
    { prami = "https://jam.omg.lol/" },
  ]
