baseURL = "/"
languageCode = "en-us"
# Example config: https://github.com/lukeorth/poison?tab=readme-ov-file#example-config
theme = "poison"
pluralizelisttitles = false

ignoreLogs = ['warning-goldmark-raw-html']

[params]
  brand = "Jam{es}"
  brand_image = "/img/me.jpg"
  description = "Computers, keyboards, Linux, gaming and misc things of interest"
  dark_mode = true
  favicon = "/img/logo.png"

  # Links to your socials.  Comment or delete any you don't need/use.
  discord_url = "https://discord.gg/nU2aEQJezE"
  email_url = "mailto:notjamesdixon@gmail.com"
  # facebook_url = "https://facebook.com"
  # flickr_url = "https://flickr.com"
  github_url = "https://github.com/lemonase/lemonase.github.io"
  # gitlab_url = "https://gitlab.com"
  # instagram_url = "https://instagram.com"
  # linkedin_url = "https://linkedin.com"
  # mastodon_url = "https://mastodon.social"
  # matrix_url = "https://matrix.org"
  telegram_url = "https://t.me/enraged_lemon"
  # tryhackme_url = "https://tryhackme.com"
  # twitter_url = "https://twitter.com"
  # x_url = "https://x.com"
  # xmpp_url = "https://xmpp.org"
  # youtube_url = "https://youtube.com"
  # signal_url = "https://signal.org"
  # bluesky_url = "https://bsky.app"

  # front page is posts
  front_page_content = ["posts"]

  # enable rss
  rss_icon = true
  rss_section = "posts"

  # MENU PLACEHOLDER
  # Menu dict keys:
  # Name:         The name to display on the menu.
  # URL:          The directory relative to the content directory.
  # HasChildren:  If the directory's files should be listed.  Default is true.
  # Limit:        If the files should be listed, how many should be shown.
  menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
  ]

  # sidebar customizations
  sidebar_bg_color = "#121122"

  # post/content customizations
  post_title_color_dark = "#3a66bd"
