baseURL = "https://lemonase.github.io/"
languageCode = "en-us"
theme = "poison"
pluralizelisttitles = false

ignoreLogs = ['warning-goldmark-raw-html']

[params]
  brand = "Jam[es?]"
  brand_image = "/img/me.jpg"
  description = "A blog for writing and reading"
  dark_mode = true

  front_page_content = ["posts"]

  # MENU PLACEHOLDER
  # Menu dict keys:
  # Name:         The name to display on the menu.
  # URL:          The directory relative to the content directory.
  # HasChildren:  If the directory's files should be listed.  Default is true.
  # Limit:        If the files should be listed, how many should be shown.
  menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
  ]
