baseURL = "/"
languageCode = "en-us"
# Example config: https://github.com/lukeorth/poison?tab=readme-ov-file#example-config
theme = "poison"
pluralizelisttitles = false

ignoreLogs = ['warning-goldmark-raw-html']

[params]
  brand = "Jam{es}"
  brand_image = "/img/me.jpg"
  description = "Computers, keyboards, Linux, gaming and misc things of interest"
  dark_mode = true
  favicon = "/img/logo.png"

  front_page_content = ["posts"]

  # MENU PLACEHOLDER
  # Menu dict keys:
  # Name:         The name to display on the menu.
  # URL:          The directory relative to the content directory.
  # HasChildren:  If the directory's files should be listed.  Default is true.
  # Limit:        If the files should be listed, how many should be shown.
  menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
  ]

  # sidebar customizations
  sidebar_bg_color = "#121122"

  # post/content customizations
  post_title_color_dark = "#3a66bd"
